### PR TITLE
support spaces in URLs with newer CURL versions

### PR DESCRIPTION
**Pull request by simonschmeisser**
see https://stackoverflow.com/questions/69254520/how-to-use-curlu-allow-space-with-curl-easy-perform
and https://github.com/ros/resource_retriever/issues/84

### CODE REVIEW

**Comment by simonschmeisser** [comment]
@v4hn would be nice to include this here and in your next build

**Review by v4hn — COMMENTED** [review]
Wouldn't the much better patch just add a
```
mod_url = std::regex_replace(mod_url, std::regex(" "), "%20");
```
? 

**EDIT (fixed code example)**

**Comment by simonschmeisser** [comment]
> Wouldn't the much better patch just add a
> 
> ```
> mod_url = std::regex_replace(mod_url, std::regex(" ", "%20");
> ```
> 
> ?

that seems too readable and sensible for c++ std library to be true

before second , is missing a ) I guess.

I'll adapt the PR tomorrow

**Comment by simonschmeisser** [comment]
ping :wink:

**Pull request merged**
